### ISSUE TITLE
1, 3, 4 

### ISSUE THREAD

**Issue by Underknowledge** [tdevs-in/devops-challenge-sample#1]
# Day 1 
Not agreeing that junky Jenkins is the right tool. (I've never used it, but at conferences you often hear that people want to get rid of their Jenkins piplines.. )
deploying GitLab, why not go for the builtin GitLab CI/CD. 
Also going further the rabbit hole I ~~expect~~ would like to see a lot of k8s, then Tekton maybe.

# Day 3
imo, Challenges like this should be set-up by a script. 
quick example:
```bash
#!/bin/bash

# Expecting here that we might want to do more often stuff with our gitlab instance, maybe fill vars here 
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
if [ -f $SCRIPTPATH/../globals ]; then
  source $SCRIPTPATH/../globals
fi

GITLABURL="${GITLABURL:-gitlab.loal}"
USERNAME="${USERNAME:-admin}"
REPO="${REPO:-Day3}"
CLONE_DIR="${CLONE_DIR:-$REPO}"

REPO_URL="https://$GITLABURL/$USERNAME/$REPO.git"


git clone $REPO_URL $CLONE_DIR
cd $CLONE_DIR

# switch to "feature-xyz" branch
git checkout -b feature-xyz
echo "Adding content to feature-xyz branch" >> sample_file.txt
# Commit and push changes to "feature-xyz" branch
git add .
git commit -m "Add changes to feature-xyz branch"
git push origin feature-xyz


# Switch back to the main branch
git checkout main
echo "Making changes to main branch" > sample_file.txt

# Commit and push changes to main branch
git add .
git commit -m "Add changes to main branch"
git push origin main

cd ..
rm -rf $CLONE_DIR
```

a  "Check My Solution" script would be nice too. 

# Day 4 
Really unsure here if Java is the right thing. I mean I'm a couple of years in the Devops world, but I never really had to touch Java. 
What level were talking bout here? Experienced engineers (Why bother with git then) or starters. 
When we talk about starters, wouldn't be shell scripting the first choice? 
Hard to say what part is ~~right~~ ok. 

When coming down to unit tests, Maybe a pick-your-poison? 
Java/python/go/node

**Comment by kasattejaswi** [comment]
Thanks for the detailed feedback. Here are some of my responses to your feedback.

On a short note, these exercises expect that you have completed your basic DevOps training and you know things around DevOps toolbelt. These exercises expect that you haven't worked on DevOps yet, that's why you are taking these exercises to gain real-world experience.

**About Day 1**: I believe Jenkins is the starting point of CI and CD. It would be great to have some hands-on on Jenkins. We can slowly climb the ladder up and move to GitHub actions where most of the tasks are already automated by the open-source community. Having Jenkins initially will help users to dive deep into automation by writing everything themselves. The first task sets the base for further exercises. And yes, there will be exercises on Kubernetes.

**About day 3**: I got some feedback from initial users. They would like to have tutorial-based solutions. I will plan to add them.

**About day 4**: A lot of organizations still use Java a lot along with Jenkins. I have seen people working on Jenkins and Java all the time. For starters, yes shell scripting would be first choice. However, they won't be writing code in Java. The application provided would simulate the application developed by a team of developers. They just need to build, test and deploy it rather than modifying the code. People who are doing exercises won't be writing unit tests. They will just execute them in pipelines.
